# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import plugs_media.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='price')),
                ('avatar', plugs_media.fields.MediaField(blank=True, max_length=100, null=True, verbose_name='avatar')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'item category',
                'verbose_name_plural': 'item categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='total')),
                ('payment_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='payment_id')),
                ('state', django_fsm.FSMField(blank=True, choices=[('CREATED', 'Created'), ('IN_PAYMENT', 'In Payment'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('CANCELED', 'Canceled'), ('INVALID', 'Invalid')], default='CREATED', max_length=50, verbose_name='state')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, verbose_name='quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=22, verbose_name='price')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugs_store.Item', verbose_name='item')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plugs_store.Order', verbose_name='order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='name')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('avatar', plugs_media.fields.MediaField(blank=True, max_length=100, null=True, verbose_name='avatar')),
            ],
            options={
                'verbose_name': 'payment type',
                'verbose_name_plural': 'payment types',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(verbose_name='address')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='fee')),
            ],
            options={
                'verbose_name': 'shipping',
                'verbose_name_plural': 'shipping',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugs_store.PaymentType'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plugs_store.Shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plugs_store.ItemCategory'),
        ),
    ]
